print('Builtin variables: ')
vars = dir()
print(vars)
print('Builtins: {}'.format(__builtins__))
print('########')
print('Warning: {}'.format(__warningregistry__))
print('########')
print('Name: {}'.format(__name__))
print('########')
print('File: {}'.format(__file__))
print('########')